[package]
name = "ffi_e"
version = "0.1.0"
edition = "2024"
build = "build.rs"

[dependencies]
eframe = "0.32.3"
egui = "0.32.3"  # plot feature not available here
egui_plot = "0.33.0"


[build-dependencies]
cc = "1.0"
